[platformio]
default_envs =
    esp32-s3-controller
    esp32-wifi-bridge
    esp32cam
src_dir = src
include_dir = include

[env]
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Werror=return-type
build_unflags =
    -std=gnu++11

[env:esp32-s3-controller]
platform = espressif32@6.12.0
board = sotm-esp32-s3-n16r8
build_src_filter =
    +<controller/>
    +<shared/>
lib_deps =
    bblanchon/ArduinoJson@^7.3.1
    gin66/FastAccelStepper@^0.31.0

[env:esp32-wifi-bridge]
platform = espressif32@6.12.0
board = esp32dev
build_src_filter =
    +<bridge/>
    +<shared/>

[env:esp32cam]
platform = espressif32@6.12.0
board = esp32cam
board_build.partitions = huge_app.csv
build_src_filter =
    +<camera/>
    +<shared/>
